const MODULE_NAME = 'TRADE';

export const CREATE_TRADE = `[${MODULE_NAME}] CREATE_TRADE`;
export const CREATE_TRADE_SUCCESS = `[${MODULE_NAME}] CREATE_TRADE_SUCCESS`;

export const GET_TRADES = `[${MODULE_NAME}] GET_TRADES`;
export const GET_TRADES_SUCCESS = `[${MODULE_NAME}] GET_TRADES_SUCCESS`;

export const SET_ERROR = `[${MODULE_NAME}] SET_ERROR`;
export const CLOSE_TRADE = `[${MODULE_NAME}] CLOSE_TRADE`;

export const CLEAR_ERROR = `[${MODULE_NAME}] CLEAR_ERROR`;