const MODULE_NAME = 'USER';

export const GET_USER = `[${MODULE_NAME}] GET_USER`;
export const SET_USER = `[${MODULE_NAME}] SET_USER`;
export const GET_USER_ERROR = `[${MODULE_NAME}] GET_USER_ERROR`;
export const GET_USER_SUCCESS = `[${MODULE_NAME}] GET_USER_SUCCESS`;
export const GET_USER_ERRORS_CLEAR = `[${MODULE_NAME}] GET_USER_ERRORS_CLEAR`;

export const REFILL_WALLET = `[${MODULE_NAME}] REFILL_WALLET`;
export const GET_WALLET = `[${MODULE_NAME}] GET_WALLET`;
export const SET_WALLET = `[${MODULE_NAME}] SET_WALLET`;

export const UPDATE_USER_INFO = `[${MODULE_NAME}] UPDATE_USER_INFO`;
export const UPDATE_USER = `[${MODULE_NAME}] UPDATE_USER`;

export const DELETE_USER = `[${MODULE_NAME}] DELETE_USER`;
export const UPDATE_USER_PASSWORD = `[${MODULE_NAME}] UPDATE_USER_PASSWORD`;