const MODULE_NAME = "CHART";

export const GET_CHART_HISTORY = `[${MODULE_NAME}] GET_CHART_HISTORY`;
export const GET_CHART_HISTORY_ERROR = `[${MODULE_NAME}] GET_CHART_HISTORY_ERROR`;
export const GET_CHART_HISTORY_SUCCESS = `[${MODULE_NAME}] GET_CHART_HISTORY_SUCCESS`;

export const GET_LISTED_CURRENCIES = `[${MODULE_NAME}] GET_LISTED_CURRENCIES`;
export const GET_LISTED_CURRENCIES_ERROR = `[${MODULE_NAME}] GET_LISTED_CURRENCIES_ERROR`;
export const GET_LISTED_CURRENCIES_SUCCESS = `[${MODULE_NAME}] GET_LISTED_CURRENCIES_SUCCESS`;

export const SET_CANDLE_OBJECT = `[${MODULE_NAME}] SET_CANDLE_OBJECT`;

export const SET_CURRENCY_POOL = `[${MODULE_NAME}] SET_CURRENCY_POOL`;

export const SET_CURRENT_CURRENCY = `[${MODULE_NAME}] SET_CURRENT_CURRENCY`;

export const SET_CURRENT_SOCKET_CURRENCY = `[${MODULE_NAME}] SET_CURRENT_SOCKET_CURRENCY`;
