const MODULE_NAME = 'CHART';

export const GET_CHART_HISTORY = `[${MODULE_NAME}] GET_CHART_HISTORY`;
export const SET_CHART_HISTORY = `[${MODULE_NAME}] SET_CHART_HISTORY`;
export const SET_CHART_HISTORY_ERROR = `[${MODULE_NAME}] SET_CHART_HISTORY_ERROR`;
export const GET_CHART_HISTORY_SUCCESS = `[${MODULE_NAME}] GET_CHART_HISTORY_SUCCESS`;
export const SET_CANDLE_OBJECT = `[${MODULE_NAME}] SET_CANDLE_OBJECT`;
export const SET_CURRENCY_POOL_ITEM = `[${MODULE_NAME}] SET_CURRENCY_POOL_ITEM`;

export const SET_CURRENT_CURRENCY = `[${MODULE_NAME}] SET_CURRENT_CURRENCY`;

export const SET_CURRENT_SOCKET_CURRENCY = `[${MODULE_NAME}] SET_CURRENT_SOCKET_CURRENCY`;